#SCRIPT FOR MERGING THE .CSV FILES GENERATED BY SEVERAL EXPERIMENTS (E.G. SENSITIVITY), EACH ONE COMPOSED OF A SET OF MC SIMULATIONS, IN A SINGLE .CSV FILE

#This function extracts a substring of a string x by keeping just the n characters from the right
substrRIGHT<-function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

#This function extracts a substring of a string x by removing the first n characters from the left
substrLEFT<-function(x, n){
  substr(x, 1, nchar(x)-n)
}

#This function merges the results obtained from the experiments (each experiment having is own subfolder in the folder "folder") and creates one file per report containing the y experiments, each composed of x MC repetitions. 
#The column names identifies the experiment and the speciic MC repetition to which each time series refers: "expYrunX" where Y is the y-th experiment and X is the x-th repetition)
generateMergedCSV<-function(folder){
  
  #Gets all the folders in the folder (each folder containing the result of the repetitions of one parameter set)
  expFolders<-list.dirs(folder,recursive=F)
  #Gives the number of experiments
  nbExperiments<-length(expFolders)
  
  #Gets all the file names containing the generated data
  allFileNames<-list.files(expFolders[1],pattern="^[a-zA-Z]+1.csv",full.names=F)
  
  #For each file
  for(fileName in allFileNames){
    #Get the first five characters of the filename
    fileNameStr<-substrLEFT(fileName,5)
    #If it is not a file containing the network of balance sheet (called BSNet)
    if(!grepl("BSNet",fileNameStr)){
      #get all the file containing the same data (one per repeated simulation)
      allFiles<-list.files(folder,pattern=paste(fileNameStr,"[0-9]",sep=""),full.names=T,recursive=T)
      # Initialize the data structure
      result<-data.frame()
      counter=1
      #For each of these files
      for(file in allFiles){
        #print(counter)
        counter=counter+1
        #If the file is not already the output of a Merger
        if(!grepl("Merged_",file)){
          # Read the data from the file
          mat<-read.csv(file,header=F)
          #If there are more than one column (i.e. when we are either looking at aggregated balance sheets or micro-data)
          if(dim(result)[1]==0){
            #Store the simulation data in the data structure
            result<-as.data.frame(mat[,1])
            colnames(result)<-"t"
          }
          #TODO
          if(dim(mat)[2]==2){
            colnames<-c("")
            multicolumn=F
            #If we are looking at an aggregated balance sheet
          }else if(grepl("agg", fileNameStr)){
            #The column names are the folllowing
            colnames<-c("CASH","DEPOSIT","CONS_GOOD","CAPITAL_GOOD","LOANS","BONDS","RESERVES", "ADV", "IBLOANS")
            #Else if we are looking at micro-data for banks
          }else if(grepl("banks", fileNameStr)){
            #Then the column names are of the format bankx with x being the number of the bank
            colnames<-sprintf("bank%03d", seq(1:(dim(mat)[2]-1)))
            #Else if we are looking at micro-data for consumption firms
          }else if(grepl("cFirms", fileNameStr)){
            #Then the column names are of the format cFirmx with x being the number of the consumption firm
            colnames<-sprintf("cFirm%03d", seq(1:(dim(mat)[2]-1)))
            #Else if we are looking at micro-data for capital firms
          }else if(grepl("kFirms", fileNameStr)){
            #Then the column names are of the format kFirmx with x being the number of the capital firm
            colnames<-sprintf("kFirm%03d", seq(1:(dim(mat)[2]-1)))
          }else if(grepl("hh", fileNameStr)){
            #Then the column names are of the format hhx with x being the number of the household
            colnames<-sprintf("hh%04d", seq(1:(dim(mat)[2]-1)))
          }
          strSpl<-strsplit(file,"/")
          
          exp<-strSpl[[1]][2]
          run<-strSpl[[1]][3]
          options(warn=-1)
          expNb<-as.numeric(substrRIGHT(exp,2))
          options(warn=0)
          if(is.na(expNb))
            expNb<-substrRIGHT(exp,1)
          options(warn=-1)
          #runNb<-as.numeric(substrLEFT(substrRIGHT(run,6),4))
          runNb<-as.numeric(gsub("\\D", "", run))
          options(warn=0)
          if(is.na(runNb))
            runNb<-substrLEFT(substrRIGHT(run,5),4)
          colnames<-paste("Exp",expNb,"Run",runNb,colnames,sep="")
          
          mat<-as.matrix(mat[,-1])
          colnames(mat)<-colnames
        
          result<-cbind(result,mat)
          
        }
      }
      write.csv(result,file=paste(folder,"/Merged_",fileNameStr,".csv",sep=""),row.names=F)
    }
  }  
}

#Compute the Sums
generateSums<-function(folder){
  allPaths<-list.files(folder,pattern="Merged_",full.names=T)
  allFileNames<-list.files(folder,pattern="Merged_",full.names=F)
  for(i in 1:length(allPaths)){
    fileName<-allFileNames[i]
    if(!grepl(".ps",fileName)){
      result<-read.csv(allPaths[i])
      colnames<-colnames(result)
      indexNames<-grep("Exp1Run1([a-zA-Z]+[0-9]*)?$",colnames)
      multicolumn=length(indexNames)!=1
      if(!grepl("agg",fileName)&multicolumn){
        tsNames<-gsub("Exp1Run1","",colnames[indexNames])
        indexExp<-grep(paste("Run1",tsNames[1],sep=""),colnames)
        nbExp<-length(indexExp)
        for(k in 1:nbExp){
          indexRuns<-grep(paste("Exp",k,"Run",sep=""),colnames)
          nbRuns<-length(indexRuns)/length(tsNames)
          for(j in 1:nbRuns){
            result<-cbind(result,rowSums(result[,grep(paste("Exp",k,"Run",j,substrLEFT(tsNames[1],3),sep=""),colnames)]))
            colnames(result)[length(colnames)+(k-1)*nbRuns+j]<-paste("Exp",k,"Run",j,"SUM",sep="")
          }
        }
        write.csv(result,file=allPaths[i],row.names=F)
      }
    }
  }
}